import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Anybody as FontSans } from "next/font/google";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import Web3ModalProvider from "@/context";
import { cn } from "@/lib/utils";
import { NavBar } from "@/components/global/nav-bar";
import { Footer } from "@/components/global/footer";

const fontSans = FontSans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-anybody",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const initialState = cookieToInitialState(config, headers().get("cookie"));
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased flex flex-col",
					fontSans.variable,
				)}
			>
				{/* <Web3ModalProvider initialState={initialState}> */}
				<NavBar />
				<div className="flex-1">{children}</div>
				<Footer />
				{/* </Web3ModalProvider> */}
			</body>
		</html>
	);
}
