name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build:ci
      env:
        AIRTABLE_API_KEY: "placeholder"
        NEXT_PUBLIC_PROJECT_ID: "placeholder"

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: oven-sh/setup-bun@v1
  #     with:
  #       bun-version: latest
  #   - run: bun install
  #   - run: bun run lint

  codeql:
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write
      steps:
        - uses: actions/checkout@v4
        - uses: github/codeql-action/init@v3
          with:
            languages: "javascript-typescript"
        - uses: github/codeql-action/autobuild@v3
        - uses: github/codeql-action/analyze@v3
